import {
	Activity,
	AlertTriangle,
	BarChart3,
	Box,
	Briefcase,
	Calendar,
	Copy,
	CornerUpRight,
	Database,
	Download,
	Eye,
	EyeOff,
	FileText,
	Folder,
	Globe,
	Image as ImageIcon,
	Layers,
	List,
	type LucideIcon,
	Mail,
	Network,
	Newspaper,
	Pencil,
	Plus,
	RefreshCw,
	Server,
	Settings as SettingsIcon,
	Tag as TagIcon,
	Trash2,
	Truck,
	Upload,
	Users as UsersIcon,
	Atom,
	Award,
	CalendarDays,
	Camera,
	ClipboardList,
	Clock,
	CloudSun,
	Coffee,
	Coins,
	CreditCard,
	Dices,
	FolderTree,
	HelpCircle,
	Key,
	LifeBuoy,
	Lock,
	Map as MapIcon,
	MapPin,
	MessageSquare,
	Monitor,
	Orbit,
	Package,
	Receipt,
	Rss,
	Search,
	Share2,
	ShoppingCart,
	Shovel,
	Target,
	Ticket,
	TrafficCone,
	Trophy,
	Video,
} from "lucide-react";

/**
 * Maps a BigTree legacy icon slug onto a Lucide component. The slugs come from
 * the original sprite-sheet keys in `core/admin/css/main.less` (icon_small_*).
 * Both the module `icon` (rendered on the Modules landing) and the module
 * action `class` glyph (rendered in the module sub-nav) draw from this same
 * vocabulary, so the map serves both. Anything unmapped falls back to <Box />.
 */
const LEGACY_ICON_MAP: Record<string, LucideIcon> = {
	// Module / content icons
	news: Newspaper,
	newspaper: Newspaper,
	tags: TagIcon,
	tag: TagIcon,
	folder: Folder,
	file: FileText,
	page: FileText,
	calendar: Calendar,
	calendar2: Calendar,
	users: UsersIcon,
	user: UsersIcon,
	image: ImageIcon,
	picture: ImageIcon,
	mail: Mail,
	email: Mail,
	world: Globe,
	globe: Globe,
	server: Server,
	gear: SettingsIcon,
	setup: SettingsIcon,
	settings: SettingsIcon,
	truck: Truck,
	car: Truck,
	list: List,
	modules: Layers,
	database: Database,
	briefcase: Briefcase,
	business: Briefcase,
	activity: Activity,
	// Action glyphs (module sub-nav / nav_icon)
	add: Plus,
	edit: Pencil,
	delete: Trash2,
	refresh: RefreshCw,
	duplicate: Copy,
	view: Eye,
	error: AlertTriangle,
	ignored: EyeOff,
	redirect: CornerUpRight,
	up: Upload,
	down: Download,
	network: Network,
	bar_graph: BarChart3,
	// Remaining BigTreeAdmin::$IconClasses glyphs (approximated with Lucide).
	token: Coins,
	export: Share2,
	help: HelpCircle,
	question: HelpCircle,
	clock: Clock,
	key: Key,
	lock_key: Lock,
	search: Search,
	computer: Monitor,
	events: CalendarDays,
	blog: Rss,
	form: ClipboardList,
	category: FolderTree,
	map: MapIcon,
	pin: MapPin,
	sports: Trophy,
	credit_card: CreditCard,
	cart: ShoppingCart,
	cash_register: Receipt,
	comments: MessageSquare,
	weather: CloudSun,
	planet: Orbit,
	mug: Coffee,
	atom: Atom,
	shovel: Shovel,
	cone: TrafficCone,
	lifesaver: LifeBuoy,
	target: Target,
	ribbon: Award,
	dice: Dices,
	ticket: Ticket,
	pallet: Package,
	camera: Camera,
	video: Video,
};

/**
 * The canonical module-icon vocabulary, mirroring `BigTreeAdmin::$IconClasses`
 * (core/inc/bigtree/admin.php). This is the exact set the legacy module
 * designer's icon picker offered, in the same order. The IconPicker renders
 * these as a grid; `iconFor` maps each onto its Lucide approximation.
 */
export const MODULE_ICON_SLUGS: string[] = [
	"gear",
	"truck",
	"token",
	"export",
	"redirect",
	"help",
	"error",
	"ignored",
	"world",
	"server",
	"clock",
	"network",
	"car",
	"key",
	"folder",
	"calendar",
	"search",
	"setup",
	"page",
	"computer",
	"picture",
	"news",
	"events",
	"blog",
	"form",
	"category",
	"map",
	"user",
	"question",
	"sports",
	"credit_card",
	"cart",
	"cash_register",
	"lock_key",
	"bar_graph",
	"comments",
	"email",
	"weather",
	"pin",
	"planet",
	"mug",
	"atom",
	"shovel",
	"cone",
	"lifesaver",
	"target",
	"ribbon",
	"dice",
	"ticket",
	"pallet",
	"camera",
	"video",
	"twitter",
	"facebook",
];

export const iconFor = (slug: string | undefined): LucideIcon => {
	if (!slug) {
		return Box;
	}

	return LEGACY_ICON_MAP[slug.toLowerCase()] ?? Box;
};
